### ISSUE TITLE
How to pass anonymous events to AppBoy via Segment server-side integration?

### ISSUE THREAD

**Issue by iancanderson** [segment-integrations/integration-appboy#28]
Hi, we are struggling to figure out an okay way to send events to App Boy for anonymous users who have not yet logged in or signed up.

Currently, we're sending these anonymous events to Segment via the HTTP API, with a generated UUID as the `anonymousId` parameter. However, these events are rejected by App Boy, because `external_id` is a required property, and this integration only sets this from the `track.userId()`, which is not present in the case of anonymous events:

https://github.com/segment-integrations/integration-appboy/blob/da86c0c0aefe52f1487b9b659d0a0df59c6686ab/lib/mapper.js#L36-L42

I see a few options:

1. In our Segment HTTP calls, we send the fake/generated UUID as `userId` instead of `anonymousId`, so the integration will pass it as the App Boy `external_id`
1. This integration's code is updated so that `external_id` is mapped from `track.userId() || track.anonymousId()`.

Option 2 seems way better for us, since it will allow us to use Segment in the way that it's meant to be, instead of passing "fake" `userId` values that aren't in our database.
Option 1 worries us because it seems like it can potentially have strange side effects for our other Segment integrations.

Any and all suggestions are welcome!

**Comment by hankim813** [comment]
cc @anoonan

**Comment by aloisbarreras** [comment]
Hey @hankim813 and @anoonan I actually had this same problem as well so went ahead and took a stab at fixing it. I opened a PR for here #29

**Comment by prestonwrthompson** [comment]
@iancanderson @aloisbarreras how are these anonymous users identified in appboy? are they also anonymous users in appboy or have they been identified with some External User ID?

I work at Appboy so I can help try to figure out a solution for this problem. Identifying users (especially anonymous ones) across multiple systems is a difficult problem, but something we are looking to make easier

**Comment by iancanderson** [comment]
@prestonwrthompson thanks for the reply!

> how are these anonymous users identified in appboy?

the way we were trying to use segment -> appboy was solely via the Segment HTTP API.

We have since removed the segment -> appboy integration in favor of using the appboy react native SDK directly for tracking and identifying users.

This is because even if we could send the anonymous ID from segment to appboy server-side, we still would have the problem mentioned by @hankim813 here: https://github.com/segment-integrations/integration-appboy/pull/29#issuecomment-290249695

I think a combination of https://github.com/segment-integrations/integration-appboy/pull/29 _plus_ a public http API for the `changeUser` functionality on AppBoy could make a server-side-only integration possible. With a `changeUser` HTTP API that took a new user identifier and a `previousId`, Segment could call `changeUser` via this integration when Segment's `/alias` endpoint is hit.

Does that make sense?

**Comment by aloisbarreras** [comment]
@iancanderson that makes sense to me, and it would be great if Appboy had this :).

@prestonwrthompson not sure how much work it would be to implement something like this on your end. Does Appboy have a preferred way to open a feature request? I'm happy to open an issue with you guys to at least get it on your road map. And this seems like more of a feature that Appboy would need to add, so we can move the discussion to an Appboy forum instead of Segment.

**Comment by hankim813** [comment]
@aloisbarreras @iancanderson yeah the problem with us falling back on `anonymousId` is that we that if someone sends `userId` +  with same `anonymousId`, we would create a dupe in Appboy. 

Normally either partner tools should have a) alias endpoint b) even better accept a reserved field for anonymousId 

I'm sure this aliasing of anon users and identified users would not be problematic if you are using _only_ appboy client side SDKs but when you have to use just using their server side api, this seems like something that Appboy would have to support on their end... otherwise we'd have to introduce a lot of workarounds at our integration layer :)

With that said, @aloisbarreras @iancanderson are you guys explicitly _NOT_ trying to use their client side SDK? we're currently building out the client side Appboy integration which would support their analytics piece via their web sdk  + support for in app push msgs + notifications

**Comment by iancanderson** [comment]
> we're currently building out the client side Appboy integration which would support their analytics piece via their web sdk + support for in app push msgs + notifications

Since we're using `react-native` and Appboy has an official react native library (where segment does not), it seemed like the easiest thing to do was to use their supported lib instead of trying to bridge to the Segment native SDKs ourselves.

**Comment by hankim813** [comment]
@iancanderson gotcha. I'm going to close this issue for now because I do not think this is something we should support without Appboy making some alias endpoint or reserved anonymousId property available as you have suggested.
